export const seedBriefs = [
  {
    name: 'TYS Batch #1',
    batchNumber: 1,
    strategist: 'Mia',
    date: '2026-06-03',
    type: 'Video',
    formatType: 'AI Animated',
    awarenessStage: 'TOF',
    adConcept: 'Black guy disney avatar',
    angle: 'What Happens when you wear ignite',
    facebookPage: 'EHIM',
    landingPage: 'PDP',
    scriptLink: '',
    finalVideoLink: 'https://www.facebook.com/61588806910493/posts/122106975939293563/',
    postId: '122106975939293563',
    status: 'launched',
    learnings: 'Ai animated black avatar vids work - need softer language (not putting them down)',
  },
  {
    name: 'TYS Batch #2',
    batchNumber: 2,
    strategist: 'Mia',
    date: '2026-06-03',
    type: 'Video',
    formatType: 'AI Animated',
    awarenessStage: 'TOF',
    adConcept: 'Stick Figure cartoon',
    angle: 'Us Vs Them',
    facebookPage: 'EHIM',
    landingPage: 'PDP',
    scriptLink: '',
    finalVideoLink: '',
    postId: '',
    status: 'launched',
    learnings: '',
  },
  {
    name: 'TYS Batch #3',
    batchNumber: 3,
    strategist: 'Mia',
    date: '2026-06-03',
    type: 'Video',
    formatType: 'UGC-Style',
    awarenessStage: 'TOF',
    adConcept: 'Text Overlay AI UGC',
    angle: 'Us Vs Them',
    facebookPage: 'EHIM',
    landingPage: 'PDP',
    scriptLink: '',
    finalVideoLink: '',
    postId: '',
    status: 'scripting',
    learnings: '',
  },
  {
    name: 'TYS Batch #4',
    batchNumber: 4,
    strategist: 'Mia',
    date: '2026-06-03',
    type: 'Video',
    formatType: 'Broll + VO',
    awarenessStage: 'TOF',
    adConcept: 'Explainer video',
    angle: 'What regular cologne is missing',
    facebookPage: 'EHIM',
    landingPage: 'PDP',
    scriptLink: '',
    finalVideoLink: '',
    postId: '',
    status: 'scripting',
    learnings: '',
  },
  {
    name: 'TYS Batch #5',
    batchNumber: 5,
    strategist: 'Mia',
    date: '2026-06-04',
    type: 'Video',
    formatType: 'AI Animated',
    awarenessStage: 'TOF',
    adConcept: 'Zac D Films',
    angle: 'the 3 pheromone compounds',
    facebookPage: 'EHIM',
    landingPage: 'PDP',
    scriptLink: '',
    finalVideoLink: '',
    postId: '',
    status: 'launched',
    learnings: '',
  },
  {
    name: 'TYS Batch #6',
    batchNumber: 6,
    strategist: 'Mia',
    date: '2026-06-04',
    type: 'Video',
    formatType: 'Broll + VO',
    awarenessStage: 'TOF',
    adConcept: 'Celebrity choosing Ignite over x',
    angle: '3 reasons why',
    facebookPage: 'EHIM',
    landingPage: 'PDP',
    scriptLink: '',
    finalVideoLink: '',
    postId: '',
    status: 'launched',
    learnings: '',
  },
  {
    name: 'TYS Batch #7',
    batchNumber: 7,
    strategist: 'Mia',
    date: '2026-06-04',
    type: 'Video',
    formatType: 'Broll + VO',
    awarenessStage: 'TOF',
    adConcept: 'Ignite Explainer',
    angle: 'What happens first time wearing ignite',
    facebookPage: 'EHIM',
    landingPage: 'PDP',
    scriptLink: '',
    finalVideoLink: '',
    postId: '',
    status: 'scripting',
    learnings: '',
  },
  {
    name: 'TYS Batch #8',
    batchNumber: 8,
    strategist: 'Mia',
    date: '2026-06-04',
    type: 'Video',
    formatType: 'Podcast-Reaction + Narrator',
    awarenessStage: 'TOF',
    adConcept: 'Deepfake KIm K',
    angle: 'Lewis Hamilton cologne - making women go feral',
    facebookPage: 'EHIM',
    landingPage: 'PDP',
    scriptLink: '',
    finalVideoLink: '',
    postId: '',
    status: 'scripting',
    learnings: '',
  },
  {
    name: 'TYS Batch #9',
    batchNumber: 9,
    strategist: 'Mia',
    date: '2026-06-04',
    type: 'Video',
    formatType: 'Podcast-Reaction + Narrator',
    awarenessStage: 'TOF',
    adConcept: 'Deepfake Shane Gillis',
    angle: 'How mid guy pulls attractive girl',
    facebookPage: 'EHIM',
    landingPage: 'PDP',
    scriptLink: '',
    finalVideoLink: '',
    postId: '',
    status: 'scripting',
    learnings: '',
  },
  {
    name: 'TYS Batch #10',
    batchNumber: 10,
    strategist: 'Mia',
    date: '2026-06-04',
    type: 'Static',
    formatType: 'Native story',
    awarenessStage: 'TOF',
    adConcept: 'It\'s not your fault',
    angle: '',
    facebookPage: 'EHIM',
    landingPage: 'PDP',
    scriptLink: '',
    finalVideoLink: '',
    postId: '',
    status: 'launched',
    learnings: '',
  },
  {
    name: 'TYS Batch #11',
    batchNumber: 11,
    strategist: 'Mia',
    date: '2026-06-05',
    type: 'Native',
    formatType: 'native story',
    awarenessStage: 'TOF',
    adConcept: 'Got His Marriage Back',
    angle: '',
    facebookPage: 'EHIM',
    landingPage: 'PDP',
    scriptLink: '',
    finalVideoLink: '',
    postId: '',
    status: 'launched',
    learnings: '',
  },
  {
    name: 'TYS Batch #12',
    batchNumber: 12,
    strategist: 'Mia',
    date: '2026-06-05',
    type: 'Video',
    formatType: 'UGC-Style',
    awarenessStage: 'TOF',
    adConcept: 'Lewis Hamilton Deepfake',
    angle: 'Reveals secret cologne',
    facebookPage: 'EHIM',
    landingPage: 'PDP',
    scriptLink: '',
    finalVideoLink: '',
    postId: '',
    status: 'scripting',
    learnings: '',
  },
  {
    name: 'TYS Batch #13',
    batchNumber: 13,
    strategist: 'Mia',
    date: '2026-06-05',
    type: 'Video',
    formatType: 'Broll + VO',
    awarenessStage: 'TOF',
    adConcept: '3 reasons why',
    angle: 'why you shouldn\'t use ignite reversal',
    facebookPage: 'EHIM',
    landingPage: 'PDP',
    scriptLink: '',
    finalVideoLink: '',
    postId: '',
    status: 'scripting',
    learnings: '',
  },
  {
    name: 'TYS Batch #14',
    batchNumber: 14,
    strategist: 'Mia',
    date: '2026-06-05',
    type: 'Static',
    formatType: 'Problem-Agitation',
    awarenessStage: 'MOF',
    adConcept: 'Ignite in Trash',
    angle: 'So good I threw it out',
    facebookPage: 'EHIM',
    landingPage: 'PDP',
    scriptLink: '',
    finalVideoLink: '',
    postId: '',
    status: 'scripting',
    learnings: '',
  },
  {
    name: 'TYS Batch #15',
    batchNumber: 15,
    strategist: 'Mia',
    date: '2026-06-05',
    type: 'Video',
    formatType: 'AI Animated',
    awarenessStage: 'TOF',
    adConcept: 'Scientists Discovery',
    angle: 'Pheromone explanation',
    facebookPage: 'EHIM',
    landingPage: 'PDP',
    scriptLink: '',
    finalVideoLink: '',
    postId: '',
    status: 'scripting',
    learnings: '',
  },
  {
    name: 'TYS Batch #16',
    batchNumber: 16,
    strategist: 'Mia',
    date: '2026-06-06',
    type: 'Video',
    formatType: 'Broll + VO',
    awarenessStage: 'TOF',
    adConcept: 'Deepfake Chris Brown + Teyana Taylor',
    angle: 'How they\'re pulling.',
    facebookPage: 'EHIM',
    landingPage: 'PDP',
    scriptLink: '',
    finalVideoLink: '',
    postId: '',
    status: 'scripting',
    learnings: '',
  },
  {
    name: 'TYS Batch #17',
    batchNumber: 17,
    strategist: 'Mia',
    date: '2026-06-06',
    type: 'Video',
    formatType: 'UGC-Style',
    awarenessStage: 'MOF',
    adConcept: 'AI News Anchor',
    angle: 'Viral Cologne',
    facebookPage: 'EHIM',
    landingPage: 'PDP',
    scriptLink: '',
    finalVideoLink: '',
    postId: '',
    status: 'scripting',
    learnings: '',
  },
  {
    name: 'TYS Batch #18',
    batchNumber: 18,
    strategist: 'Mia',
    date: '2026-06-06',
    type: 'Video',
    formatType: 'Podcast-Reaction + Narrator',
    awarenessStage: 'TOF',
    adConcept: 'Deepfake Sophie Rain + Howie Mandel',
    angle: 'Reveals why she\'s dating him (it\'s the cologne)',
    facebookPage: 'EHIM',
    landingPage: 'PDP',
    scriptLink: '',
    finalVideoLink: '',
    postId: '',
    status: 'scripting',
    learnings: '',
  },
  {
    name: 'TYS Batch #19',
    batchNumber: 19,
    strategist: 'Mia',
    date: '2026-06-06',
    type: 'Video',
    formatType: 'UGC-Style',
    awarenessStage: 'TOF',
    adConcept: 'AI UGC TED TALK',
    angle: 'Every man in their 40s should know this',
    facebookPage: 'EHIM',
    landingPage: 'PDP',
    scriptLink: '',
    finalVideoLink: '',
    postId: '',
    status: 'scripting',
    learnings: '',
  },
  {
    name: 'TYS Batch #20',
    batchNumber: 20,
    strategist: 'Mia',
    date: '2026-06-06',
    type: 'Video',
    formatType: 'AI Animated',
    awarenessStage: 'TOF',
    adConcept: 'Explainer video',
    angle: 'why mid guys are pulling the hottest girls',
    facebookPage: 'EHIM',
    landingPage: 'PDP',
    scriptLink: '',
    finalVideoLink: '',
    postId: '',
    status: 'scripting',
    learnings: '',
  },
  {
    name: 'TYS Batch #21',
    batchNumber: 21,
    strategist: 'Mia',
    date: '2026-06-06',
    type: 'Video',
    formatType: 'Broll + VO',
    awarenessStage: 'MOF',
    adConcept: '3 reasons why',
    angle: 'negative to positive',
    facebookPage: 'EHIM',
    landingPage: 'PDP',
    scriptLink: '',
    finalVideoLink: '',
    postId: '',
    status: 'scripting',
    learnings: '',
  },
  {
    name: 'TYS Batch #22',
    batchNumber: 22,
    strategist: 'Mia',
    date: '2026-06-07',
    type: 'Native',
    formatType: 'Long-Form Story',
    awarenessStage: 'TOF',
    adConcept: '',
    angle: 'Insecure short guy uses ignite',
    facebookPage: 'EHIM',
    landingPage: 'PDP',
    scriptLink: '',
    finalVideoLink: '',
    postId: '',
    status: 'launched',
    learnings: '',
  },
  {
    name: 'TYS Batch #23',
    batchNumber: 23,
    strategist: 'Mia',
    date: '2026-06-07',
    type: 'Native',
    formatType: 'Long-Form Story',
    awarenessStage: 'TOF',
    adConcept: 'You Never Had ED',
    angle: '',
    facebookPage: 'EHIM',
    landingPage: 'PDP',
    scriptLink: '',
    finalVideoLink: '',
    postId: '',
    status: 'launched',
    learnings: '',
  },
  {
    name: 'TYS Batch #24',
    batchNumber: 24,
    strategist: 'Mia',
    date: '2026-06-07',
    type: 'Native',
    formatType: 'Long-Form Story',
    awarenessStage: 'TOF',
    adConcept: 'Self Rejection Reframe',
    angle: 'Bald Guy Couldn\'t get Women',
    facebookPage: 'EHIM',
    landingPage: 'PDP',
    scriptLink: '',
    finalVideoLink: '',
    postId: '',
    status: 'launched',
    learnings: '',
  },
  {
    name: 'TYS Batch #25',
    batchNumber: 25,
    strategist: 'Mia',
    date: '2026-06-08',
    type: 'Native',
    formatType: 'Long-Form Story',
    awarenessStage: 'TOF',
    adConcept: '',
    angle: 'Men Feeling lonely - pay prositutes for intercourse',
    facebookPage: 'EHIM',
    landingPage: 'PDP',
    scriptLink: '',
    finalVideoLink: '',
    postId: '',
    status: 'launched',
    learnings: '',
  },
  {
    name: 'TYS Batch #26',
    batchNumber: 26,
    strategist: 'Mia',
    date: '2026-06-09',
    type: 'Video',
    formatType: 'Broll + VO',
    awarenessStage: 'TOF',
    adConcept: 'Pheromone Mechanism Explainer',
    angle: 'How older men are dating younger women',
    facebookPage: 'EHIM',
    landingPage: 'PDP',
    scriptLink: '',
    finalVideoLink: '',
    postId: '',
    status: 'scripting',
    learnings: '',
  },
  {
    name: 'TYS Batch #27',
    batchNumber: 27,
    strategist: 'Mia',
    date: '2026-06-09',
    type: 'Video',
    formatType: 'Podcast-Reaction + Narrator',
    awarenessStage: 'TOF',
    adConcept: 'MGK DeepFake',
    angle: 'How MGK was able to pull Megan Fox',
    facebookPage: 'EHIM',
    landingPage: 'PDP',
    scriptLink: '',
    finalVideoLink: '',
    postId: '',
    status: 'scripting',
    learnings: '',
  },
  {
    name: 'TYS Batch #28',
    batchNumber: 28,
    strategist: 'Mia',
    date: '2026-06-09',
    type: 'Video',
    formatType: 'Broll + VO',
    awarenessStage: 'TOF',
    adConcept: 'Explainer',
    angle: 'How mid guys are pulling 10/10s',
    facebookPage: 'EHIM',
    landingPage: 'PDP',
    scriptLink: '',
    finalVideoLink: '',
    postId: '',
    status: 'scripting',
    learnings: '',
  },
  {
    name: 'TYS Batch #29',
    batchNumber: 29,
    strategist: 'Mia',
    date: '2026-06-09',
    type: 'Video',
    formatType: 'AI Animated',
    awarenessStage: 'TOF',
    adConcept: 'Disney Style Animation',
    angle: 'Man in 50s, divorced finds discovers Ignite',
    facebookPage: 'EHIM',
    landingPage: 'PDP',
    scriptLink: '',
    finalVideoLink: '',
    postId: '',
    status: 'scripting',
    learnings: '',
  },
  {
    name: 'TYS Batch #30',
    batchNumber: 30,
    strategist: 'Mia',
    date: '2026-06-11',
    type: 'Video',
    formatType: 'AI Animated',
    awarenessStage: 'TOF',
    adConcept: 'Disney style Animation',
    angle: 'Lonely Divorced Man in 50s, discovers ignite',
    facebookPage: 'EHIM',
    landingPage: 'PDP',
    scriptLink: '',
    finalVideoLink: '',
    postId: '',
    status: 'scripting',
    learnings: '',
  },
  {
    name: 'TYS Batch #31',
    batchNumber: 31,
    strategist: 'Mia',
    date: '2026-06-10',
    type: 'Video',
    formatType: 'AI Animated',
    awarenessStage: 'TOF',
    adConcept: 'Black guy disney avatar',
    angle: 'What happens when you wear ingite',
    facebookPage: 'EHIM',
    landingPage: 'PDP',
    scriptLink: '',
    finalVideoLink: '',
    postId: '',
    status: 'scripting',
    learnings: '',
  },
  {
    name: 'TYS Batch #32',
    batchNumber: 32,
    strategist: 'Mia',
    date: '2026-06-10',
    type: 'Video',
    formatType: 'AI Animated',
    awarenessStage: 'TOF',
    adConcept: 'Zac D Films',
    angle: 'How older men are dating younger women',
    facebookPage: 'EHIM',
    landingPage: 'PDP',
    scriptLink: '',
    finalVideoLink: '',
    postId: '',
    status: 'scripting',
    learnings: '',
  },
  {
    name: 'TYS Batch #33',
    batchNumber: 33,
    strategist: 'Mia',
    date: '2026-06-11',
    type: 'Video',
    formatType: 'Broll + VO',
    awarenessStage: 'TOF',
    adConcept: 'Margot Robbie Deepfake',
    angle: 'Margot Robbie Leo Di Caprio wolf of wall street movie',
    facebookPage: 'EHIM',
    landingPage: 'PDP',
    scriptLink: '',
    finalVideoLink: '',
    postId: '',
    status: 'scripting',
    learnings: '',
  },
  {
    name: 'TYS Batch #34',
    batchNumber: 34,
    strategist: 'Mia',
    date: '2026-06-11',
    type: 'Video',
    formatType: 'Broll + VO',
    awarenessStage: 'TOF',
    adConcept: 'Alex Cooper deepfake',
    angle: 'This cologne makes me so freaky',
    facebookPage: 'EHIM',
    landingPage: 'PDP',
    scriptLink: '',
    finalVideoLink: '',
    postId: '',
    status: 'scripting',
    learnings: '',
  },
  {
    name: 'TYS Batch #35',
    batchNumber: 35,
    strategist: 'Mia',
    date: '2026-06-11',
    type: 'Video',
    formatType: 'Broll + VO',
    awarenessStage: 'TOF',
    adConcept: 'Alix Earle Deepfake',
    angle: 'Alix Earle x Tom Brady',
    facebookPage: 'EHIM',
    landingPage: 'PDP',
    scriptLink: '',
    finalVideoLink: '',
    postId: '',
    status: 'scripting',
    learnings: '',
  },
  {
    name: 'TYS Batch #36',
    batchNumber: 36,
    strategist: 'Mia',
    date: '2026-06-11',
    type: 'Video',
    formatType: 'UGC-Style',
    awarenessStage: 'MOF',
    adConcept: 'The Fragrance Plug AI UGC Deepfake',
    angle: 'Cologne rating',
    facebookPage: 'EHIM',
    landingPage: 'PDP',
    scriptLink: '',
    finalVideoLink: '',
    postId: '',
    status: 'scripting',
    learnings: '',
  },
  {
    name: 'TYS Batch #37',
    batchNumber: 37,
    strategist: 'Mia',
    date: '2026-06-11',
    type: 'Video',
    formatType: 'Broll + VO',
    awarenessStage: 'TOF',
    adConcept: 'Steve Harvey  game show Deepfake',
    angle: 'Cologne that makes her wet.',
    facebookPage: 'EHIM',
    landingPage: 'PDP',
    scriptLink: '',
    finalVideoLink: '',
    postId: '',
    status: 'scripting',
    learnings: '',
  },
  {
    name: 'TYS Batch #38',
    batchNumber: 38,
    strategist: 'Mia',
    date: '2026-06-12',
    type: 'Video',
    formatType: 'AI Animated',
    awarenessStage: 'TOF',
    adConcept: 'Claymation',
    angle: 'You\'re not ugly, You just don\'t have a pheromone cologne',
    facebookPage: 'EHIM',
    landingPage: 'PDP',
    scriptLink: '',
    finalVideoLink: '',
    postId: '',
    status: 'scripting',
    learnings: '',
  },
  {
    name: 'TYS Batch #39',
    batchNumber: 39,
    strategist: 'Mia',
    date: '2026-06-12',
    type: 'Native',
    formatType: 'Long-Form Story',
    awarenessStage: 'TOF',
    adConcept: 'the gooners wake up call',
    angle: 'Single man in 30s thinks hes meant to be single, copes with onlyfans subs',
    facebookPage: 'EHIM',
    landingPage: 'PDP',
    scriptLink: '',
    finalVideoLink: '',
    postId: '',
    status: 'scripting',
    learnings: '',
  },
  {
    name: 'TYS Batch #40',
    batchNumber: 40,
    strategist: 'Mia',
    date: '2026-06-12',
    type: 'Video',
    formatType: 'UGC-Style',
    awarenessStage: 'TOF',
    adConcept: 'AI UGC black man',
    angle: 'The type of man who gets all the girls is the one who wears ignite',
    facebookPage: 'EHIM',
    landingPage: 'PDP',
    scriptLink: '',
    finalVideoLink: '',
    postId: '',
    status: 'scripting',
    learnings: '',
  },
  {
    name: 'TYS Batch #41',
    batchNumber: 41,
    strategist: 'Mia',
    date: '2026-06-15',
    type: 'Video',
    formatType: 'Broll + VO',
    awarenessStage: 'TOF',
    adConcept: 'Beyonce Deepfake',
    angle: '',
    facebookPage: 'EHIM',
    landingPage: 'PDP',
    scriptLink: '',
    finalVideoLink: '',
    postId: '',
    status: 'scripting',
    learnings: '',
  },
  {
    name: 'TYS Batch #42',
    batchNumber: 42,
    strategist: 'Mia',
    date: '2026-06-15',
    type: 'Video',
    formatType: 'Broll + VO',
    awarenessStage: 'TOF',
    adConcept: 'Rihanna Deepfake',
    angle: '',
    facebookPage: 'EHIM',
    landingPage: 'PDP',
    scriptLink: '',
    finalVideoLink: '',
    postId: '',
    status: 'scripting',
    learnings: '',
  },
  {
    name: 'TYS Batch #43',
    batchNumber: 43,
    strategist: 'Mia',
    date: '2026-06-15',
    type: 'Video',
    formatType: 'Broll + VO',
    awarenessStage: 'TOF',
    adConcept: 'Alix Earle Tom Brady',
    angle: '',
    facebookPage: 'EHIM',
    landingPage: 'PDP',
    scriptLink: '',
    finalVideoLink: '',
    postId: '',
    status: 'scripting',
    learnings: '',
  },
  {
    name: 'TYS Batch #44',
    batchNumber: 44,
    strategist: 'Mia',
    date: '2026-06-16',
    type: 'Video',
    formatType: 'AO Animated',
    awarenessStage: 'TOF',
    adConcept: 'Claymation',
    angle: 'The missing piece for men over 50',
    facebookPage: 'EHIM',
    landingPage: 'PDP',
    scriptLink: '',
    finalVideoLink: '',
    postId: '',
    status: 'scripting',
    learnings: '',
  },
  {
    name: 'TYS Batch #45',
    batchNumber: 45,
    strategist: 'Mia',
    date: '2026-06-16',
    type: 'Video',
    formatType: 'AI Animated',
    awarenessStage: 'TOF',
    adConcept: 'Disney avatar',
    angle: 'single black man in 50s uses ignite',
    facebookPage: 'EHIM',
    landingPage: 'PDP',
    scriptLink: '',
    finalVideoLink: '',
    postId: '',
    status: 'scripting',
    learnings: '',
  },
  {
    name: 'TYS Batch #46',
    batchNumber: 46,
    strategist: 'Mia',
    date: '2026-06-16',
    type: 'Video',
    formatType: 'AI Animated',
    awarenessStage: 'TOF',
    adConcept: 'Disney avatar',
    angle: 'single black man in 50s uses ignite',
    facebookPage: 'EHIM',
    landingPage: 'PDP',
    scriptLink: '',
    finalVideoLink: '',
    postId: '',
    status: 'scripting',
    learnings: '',
  },
  {
    name: 'TYS Batch #47',
    batchNumber: 47,
    strategist: 'Mia',
    date: '2026-06-17',
    type: 'Native',
    formatType: 'Long Form Story',
    awarenessStage: 'TOF',
    adConcept: 'Single men in 40s',
    angle: 'Are some men meant to be single?',
    facebookPage: 'EHIM',
    landingPage: 'PDP',
    scriptLink: '',
    finalVideoLink: '',
    postId: '',
    status: 'scripting',
    learnings: '',
  },
  {
    name: 'TYS Batch #48',
    batchNumber: 48,
    strategist: 'Mia',
    date: '2026-06-17',
    type: 'Video',
    formatType: 'AI Podcast',
    awarenessStage: 'TOF',
    adConcept: 'Angela White Deepfake',
    angle: 'This cologne makes her finish in bed',
    facebookPage: 'EHIM',
    landingPage: 'PDP',
    scriptLink: '',
    finalVideoLink: '',
    postId: '',
    status: 'scripting',
    learnings: '',
  },
  {
    name: 'TYS Batch #49',
    batchNumber: 49,
    strategist: 'Mia',
    date: '2026-06-17',
    type: 'Video',
    formatType: 'Broll + VO',
    awarenessStage: 'TOF',
    adConcept: 'Lena the plug',
    angle: 'She can\'t stop finishing',
    facebookPage: 'EHIM',
    landingPage: 'PDP',
    scriptLink: '',
    finalVideoLink: '',
    postId: '',
    status: 'scripting',
    learnings: '',
  },
  {
    name: 'TYS Batch #50',
    batchNumber: 50,
    strategist: 'Mia',
    date: '2026-06-18',
    type: 'Video',
    formatType: 'AI UGC Podcast',
    awarenessStage: 'TOF',
    adConcept: 'Deepfake',
    angle: 'Why she\'s dating a guy in his 60s',
    facebookPage: 'EHIM',
    landingPage: 'PDP',
    scriptLink: '',
    finalVideoLink: '',
    postId: '',
    status: 'scripting',
    learnings: '',
  },
  {
    name: 'TYS Batch #51',
    batchNumber: 51,
    strategist: 'Mia',
    date: '2026-06-18',
    type: 'Video',
    formatType: 'AI UGC Podcast',
    awarenessStage: 'TOF',
    adConcept: 'Deepfake',
    angle: 'Makes her finish in bed',
    facebookPage: 'EHIM',
    landingPage: 'PDP',
    scriptLink: '',
    finalVideoLink: '',
    postId: '',
    status: 'scripting',
    learnings: '',
  },
  {
    name: 'TYS Batch #52',
    batchNumber: 52,
    strategist: 'Mia',
    date: '2026-06-17',
    type: 'Static',
    formatType: 'Headline Test',
    awarenessStage: 'BOF',
    adConcept: 'Bacarrat Inspired fragrnace',
    angle: 'Benefits',
    facebookPage: 'EHIM',
    landingPage: 'PDP',
    scriptLink: '',
    finalVideoLink: '',
    postId: '',
    status: 'scripting',
    learnings: '',
  },
  {
    name: 'TYS Batch #53',
    batchNumber: 53,
    strategist: 'Mia',
    date: '2026-06-17',
    type: 'Static',
    formatType: 'Female holding bottle',
    awarenessStage: 'BOF',
    adConcept: 'White girl',
    angle: 'What ignite does to a girl',
    facebookPage: 'EHIM',
    landingPage: 'PDP',
    scriptLink: '',
    finalVideoLink: '',
    postId: '',
    status: 'scripting',
    learnings: '',
  },
  {
    name: 'TYS Batch #54',
    batchNumber: 54,
    strategist: 'Mia',
    date: '2026-06-17',
    type: 'Static',
    formatType: 'Female holding bottle',
    awarenessStage: 'BOF',
    adConcept: 'Black Girl',
    angle: 'What ignite does to a girl',
    facebookPage: 'EHIM',
    landingPage: 'PDP',
    scriptLink: '',
    finalVideoLink: '',
    postId: '',
    status: 'scripting',
    learnings: '',
  },
  {
    name: 'TYS Batch #55',
    batchNumber: 55,
    strategist: 'Mia',
    date: '2026-06-18',
    type: 'Video',
    formatType: 'AI Animated',
    awarenessStage: 'TOF',
    adConcept: 'Black Man Disney Avatar',
    angle: 'the missing piece for men over 40',
    facebookPage: 'EHIM',
    landingPage: 'PDP',
    scriptLink: '',
    finalVideoLink: '',
    postId: '',
    status: 'scripting',
    learnings: '',
  },
  {
    name: 'TYS Batch #56',
    batchNumber: 56,
    strategist: 'Mia',
    date: '2026-06-18',
    type: 'Video',
    formatType: 'AI Animated',
    awarenessStage: 'TOF',
    adConcept: 'Black Man Disney Avatar',
    angle: 'the missing piece for men over 40',
    facebookPage: 'EHIM',
    landingPage: 'PDP',
    scriptLink: '',
    finalVideoLink: '',
    postId: '',
    status: 'scripting',
    learnings: '',
  },
  {
    name: 'TYS Batch #57',
    batchNumber: 57,
    strategist: 'Mia',
    date: '2026-06-16',
    type: 'Video',
    formatType: 'Broll + VO',
    awarenessStage: 'TOF',
    adConcept: 'Leo Di Caprio, Lewis Hamilton, Chris brown, Asap Rocky',
    angle: 'Celebrity secret colognes',
    facebookPage: 'EHIM',
    landingPage: 'PDP',
    scriptLink: '',
    finalVideoLink: '',
    postId: '',
    status: 'scripting',
    learnings: '',
  },
  {
    name: 'TYS Batch #58',
    batchNumber: 58,
    strategist: 'Mia',
    date: '2026-06-19',
    type: 'Video',
    formatType: 'AI Animated',
    awarenessStage: 'MOF',
    adConcept: 'AI Bottle + pheromone compound avatars',
    angle: 'The three compounds your cologne is missing',
    facebookPage: 'EHIM',
    landingPage: 'PDP',
    scriptLink: '',
    finalVideoLink: '',
    postId: '',
    status: 'scripting',
    learnings: '',
  },
  {
    name: 'TYS Batch #59',
    batchNumber: 59,
    strategist: 'Mia',
    date: '2026-06-19',
    type: 'Video',
    formatType: 'AI Animated',
    awarenessStage: 'TOF',
    adConcept: 'Zac D FIlms',
    angle: 'You\'re not meant to be single',
    facebookPage: 'EHIM',
    landingPage: 'PDP',
    scriptLink: '',
    finalVideoLink: '',
    postId: '',
    status: 'scripting',
    learnings: '',
  },
  {
    name: 'TYS Batch #60',
    batchNumber: 60,
    strategist: 'Mia',
    date: '2026-06-19',
    type: 'Video',
    formatType: 'AI Animated',
    awarenessStage: 'TOF',
    adConcept: 'Claymation',
    angle: 'Why Women Aren\'t attracted to you anymore',
    facebookPage: 'EHIM',
    landingPage: 'PDP',
    scriptLink: '',
    finalVideoLink: '',
    postId: '',
    status: 'scripting',
    learnings: '',
  },
]
